import psutil
from datetime import datetime

# Function to get disk usage for all drives
def get_drive_info():
    drives = psutil.disk_partitions()
    total_size = 0
    used_size = 0
    free_size = 0

    for drive in drives:
        try:
            usage = psutil.disk_usage(drive.mountpoint)
            total_size += usage.total
            used_size += usage.used
            free_size += usage.free
        except PermissionError:
            # Handle drives that can't be accessed
            continue

    return total_size, used_size, free_size

# Convert bytes to GB and TB
def bytes_to_gb_tb(bytes):
    gb = bytes / (1024 ** 3)
    tb = bytes / (1024 ** 4)
    return gb, tb

# Generate HTML report
def generate_html_report(total, used, free):
    total_gb, total_tb = bytes_to_gb_tb(total)
    used_gb, used_tb = bytes_to_gb_tb(used)
    free_gb, free_tb = bytes_to_gb_tb(free)

    # Get the current date and time
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    html_content = f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Disk Space Report</title>
            <link rel="stylesheet" href="styles.css">

            <!-- Open Graph Meta Tags -->
            <meta property="og:title" content="Disk Space Report" />
            <meta property="og:description" content="Check the current disk space usage on your system." />
            <meta property="og:image" content="URL_TO_AN_IMAGE" /> <!-- Replace with a valid image URL -->
            <meta property="og:url" content="http://diskspacereport.s3-website-us-east-1.amazonaws.com/disk_space_report.html" />
            <meta property="og:type" content="website" />
        </head>
        <body>
            <div class="container">
                <h1>Disk Space Report</h1>
                <p><strong>Report Generated On:</strong> {current_time}</p>
                <div>
                    <p><strong>Total Size:</strong> {total_gb:.2f} GB ({total_tb:.2f} TB)</p>
                    <p><strong>Used Space:</strong> {used_gb:.2f} GB ({used_tb:.2f} TB)</p>
                    <p><strong>Free Space:</strong> {free_gb:.2f} GB ({free_tb:.2f} TB)</p>
                </div>
            </div>
            <div class="footer">
                <p>Report generated by Disk Space Checker made by BreadTheRipper</p>
            </div>
        </body>
        </html>
    """
    with open("disk_space_report.html", "w") as file:
        file.write(html_content)

if __name__ == "__main__":
    total, used, free = get_drive_info()
    generate_html_report(total, used, free)